# Generated by Django 4.0 on 2022-10-26 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locaties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Fk_departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.departament')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('CellPhone', models.TextField()),
                ('Email', models.TextField(max_length=90)),
                ('Password', models.TextField(max_length=20)),
                ('Rol', models.CharField(default='[ROLE_USUARIO]', max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('Condition', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo_artist',
            fields=[
                ('Id_artist', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Cellphone', models.TextField()),
                ('Direction', models.TextField()),
                ('Email', models.TextField(max_length=90)),
                ('Experience', models.CharField(max_length=3)),
                ('Description', models.TextField(blank=True, default='', max_length=150)),
                ('Password', models.TextField(max_length=20)),
                ('Rol', models.CharField(default='[ROLE_TATUADOR]', max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('Condition', models.CharField(default='A', max_length=1)),
                ('Departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.departament')),
                ('Locaties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.locaties')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('Id_quotes', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Img', models.ImageField(upload_to='')),
                ('Description', models.CharField(default='', max_length=150)),
                ('Tattoo_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.tattoo_artist')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.users')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('Id_likes', models.BigAutoField(primary_key=True, serialize=False)),
                ('Counter_likes', models.IntegerField()),
                ('Tattoo_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.tattoo_artist')),
            ],
        ),
        migrations.CreateModel(
            name='briefcase_artist',
            fields=[
                ('Id_briefcase', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date_publication', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 11, 1, 5, 720273))),
                ('Img', models.ImageField(upload_to='')),
                ('Description', models.TextField(blank=True, default='', max_length=150)),
                ('Tattoo_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tatoo.tattoo_artist')),
            ],
        ),
    ]
