# Generated by Django 4.0 on 2022-10-18 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0003_auto_20221012_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotatuadores',
            name='rol',
            field=models.CharField(default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='registrousuarios',
            name='rol',
            field=models.CharField(default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='portafolio_tatuadores',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 11, 32, 43, 976637)),
        ),
    ]
